### ISSUE TITLE
[User Story] As a user, I want to be able to create an account

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/evolabsPOC#1]
## Acceptance Criteria

I want to be able to create an account to login to my profile

## Tasks

- [ ] Import Authenication module
- [ ] Copy Login Screens
- [ ] Change Base template
- [ ] Test Sign up
- [ ] Test Sign out
- [ ] Test Login page
