### ISSUE TITLE
[User Story] As a user, I want to be able to edit my profile

### ISSUE THREAD

**Issue by desousamario85** [desousamario85/evolabsPOC#3]
## Acceptance Criteria

I want to be able to update my profile setting on my account, such as delivery address and telephone number

## Tasks

- [ ] Create Profile page
- [ ] Create form to allow users' to update their profile
- [ ] Test form, by changing user details
